<?php

namespace techcampBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampRepository extends EntityRepository
{
}
